name: Build and test code

on: push

jobs:
  test-code:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Build and test
      uses: actions/setup-node@v1
      with: 
        node-version: '12.16.1'
    - runs: npm ci
    - runs: npm run build --if-present
    - runs: npm test