name: Build and test code
#- run: npm run build --if-present
on: push

jobs:
  test-code:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Build and test
      uses: actions/setup-node@v1
      with: 
        node-version: '12.16.1'
    - run: npm ci
    - run: npm test
